[package]
name = "wgputil"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.22.0"
image = "0.25.6"
log = "0.4.27"
pollster = "0.4.0"
thiserror = "2.0.12"
wgpu = "24.0.3"
winit = "0.30.9"
